Repository 2025-Techeer-Summer-Bootcamp-Team-J/Backend, pull requests merged in 2025-07, with the labels that each got.

#2 [set] docker: redis, mysql, fastapi 세팅 완료
  .gitignore
  .python-version
  Dockerfile
  README.md
  config/__init__.py
  config/asgi.py
  config/settings.py
  config/settings/__init__.py
  config/settings/base.py
  config/settings/dev.py
  config/settings/prod.py
  config/urls.py
  config/wsgi.py
  docker-compose.yml
  main.py
  manage.py
  post/__init__.py
  post/admin.py
  post/apps.py
  post/migrations/__init__.py
  post/models.py
  post/tests.py
  post/urls.py
  post/views.py
  pyproject.toml
  requirements.txt
  uv.lock
  wait_mysql.py
Labels: setting

#4 Update README.md
  README.md
Labels: documentation

#25 [feat]: 어드민용 API 구현/#8
  Dockerfile
  api/endpoints/admin.py
  api/endpoints/post.py
  api/router.py
  main.py
  models/diagnosis.py
  models/diseases.py
  models/post.py
  models/skintype.py
  models/symptom.py
  models/user.py
  requirements.txt
  schema/diseases.py
  schema/post.py
  schema/skintype.py
  services/diseases.py
  services/post.py
  services/skintype.py
Labels: feat

#34 [SET] cadvisor 세팅 완료 #3
  crud/post.py
  docker-compose.yml
  prometheus.yml
Labels: setting

#35 [patch] .env 수정 #4
  Dockerfile
  database/database.py
  docker-compose.yml
  pyproject.toml
  requirements.txt
  uv.lock
Labels: patch

#42 [Feat]nginx 세팅 및 구현/#13
  api/endpoints/diagnosis.py
  docker-compose.yml
  generate-ssl.sh
  nginx.conf
  requirements.txt
Labels: feat

#49 [Feat] 진단 정보 삭제 api 구현/#15
  api/endpoints/diagnosis.py
  api/endpoints/diseases.py
  docker-compose.yml
  main.py
  requirements.txt
  services/diagnosis.py
  services/diseases.py
Labels: feat

#53 [feat]: cors 문제 해결/#19
  main.py
Labels: feat

#59 [set] ci 파일 작성 완료 #5
  .github/workflows/ci.yml
Labels: setting

#60 [bug]: 비동기 처리 수정 및 응답데이터 수정/#2
  api/endpoints/admin.py
  api/endpoints/diagnosis.py
  config/celery.py
  main.py
  models/diagnosis.py
  schema/diagnosis.py
  services/diagnosis.py
  tasks/diagnosis.py
Labels: bug

#61 [Feat] 자회선 조회 api 구현 /#18
  api/endpoints/uv_index.py
  api/router.py
  main.py
  pyproject.toml
  requirements.txt
  schema/uv_index.py
  services/uv_index.py
Labels: feat

#67 [Refactor] 1시간 마다 자외선 지수 조회후 저장하는 스케쥴링 추가/#2
  api/endpoints/uv_index.py
  celerybeat-schedule-shm
  celerybeat-schedule-wal
  config/celery.py
  docker-compose.yml
  models/uv_index.py
  requirements.txt
  schema/uv_index.py
  services/uv_index.py
  tasks/__init__.py
  tasks/uv_index.py
Labels: Refactoring

#73 [Feat] 진단 세부 내용 조회 api 구현 /#22
  api/endpoints/diagnosis.py
  celerybeat-schedule-shm
  celerybeat-schedule-wal
  requirements.txt
  schema/detailed_disease_info.py
  schema/diagnosis.py
  services/diagnosis.py
  tasks/diagnosis.py
Labels: feat

#75 [feat]: api 테스트및 수정 /#24
  api/endpoints/diagnosis.py
  api/endpoints/diseases.py
  api/endpoints/user.py
  api/endpoints/uv_index.py
  celerybeat-schedule-shm
  celerybeat-schedule-wal
  config/settings.py
  models/__init__.py
  models/diagnosis.py
  models/user.py
  schema/detailed_disease_info.py
  schema/diagnosis.py
  schema/diagnosis_save.py
  schema/diseases.py
  services/dashboard.py
  services/diagnosis.py
  services/diseases.py
  services/skintype.py
  tasks/__init__.py
  test_image.jpg
Labels: feat

#84 [Feat] 프롬프팅 수정및 gemini 버전 수정/#26
  api/endpoints/diagnosis.py
  celerybeat-schedule-shm
  celerybeat-schedule-wal
  certbot/conf/.certbot.lock
  models/diagnosis.py
  schema/diagnosis_save.py
  services/diagnosis.py
Labels: feat

#85 [set] Google cloud Storage에 이미지 올리는 기능 추가 #7
  .gitignore
  api/endpoints/diagnosis.py
  celerybeat-schedule-shm
  celerybeat-schedule-wal
  crud/storage.py
  docker-compose.yml
  schema/diagnosis_save.py
  services/diagnosis.py
  tasks/diagnosis.py
Labels: Refactoring

#114 [Feat] 피부 유형 분석 API 수정 #30
  api/endpoints/admin.py
  input/original.jpg
  output/brown_area.jpg
  output/red_area.jpg
  output/response_json.txt
  output/roi_outline_map.jpg
  output/rough_area.jpg
  output/skin_analysis_overlay.jpg
  output/texture_enhanced_blackheads.jpg
  output/texture_enhanced_bw.jpg
  output/texture_enhanced_lines.jpg
  output/texture_enhanced_oily_area.jpg
  output/texture_enhanced_pores.jpg
  output/water_area.jpg
  requirements.txt
  services/picture_merge.py
  services/skin_score_graph.py
  services/skintype.py
Labels: feat

#112 [Set] RAG 세팅/#8 (수정 예정)
  requirements.txt
  scripts/firestore_seed.py
  services/diagnosis.py
  services/firestore_vector.py
  services/rag.py
Labels: feat

#118 [Feat] RAG 테스트 성공/#32
  Dockerfile
  certbot/conf/.certbot.lock
  requirements.txt
  scripts/clear_firestore_collection.py
  scripts/crawl_to_firestore.py
  scripts/firestore_seed.py
  scripts/test_firestore_and_rag.py
  services/diagnosis.py
  services/disease_store.py
  services/firestore_vector.py
  services/rag.py
  urls.csv
Labels: setting

#132 [feat] 미들웨어 api key 인증 시스템 추가 #36
  main.py
Labels: feat

#131 Feat: AI 모델 수정 및 API 수정 /#35
  .gitignore
  Dockerfile
  api/endpoints/diagnosis.py
  requirements.txt
  services/local_diagnosis.py
  tasks/diagnosis.py
Labels: feat
